name: TutorialPlugin
version: '${project.version}'
main: me.nowordsmakesense.tutorialplugin.TutorialPlugin
api-version: 1.20
authors: [ WordsDontMakeSense ]
description: This is my tutorial plugin!
commands:
  tutorial:
    usage: /tutorial
    permission: tutorialplugin.tutorial
    description: Main Tutorial Plugin Command
    aliases:
      - tut
      - tl